### ISSUE TITLE
Publish libraries to nuget

### ISSUE THREAD

**Issue by feinoujc** [M-Files/MFilesSamplesAndLibraries#11]
Is there any plan to publish the libraries to public nuget? 

I used github actions on a fork to run ci and push to a private nuget feed, and I am willing to contribute this back to this project if there is interest (the maintainer would just need to manage the nuget account/api key)

https://github.com/NCARB/MFilesSamplesAndLibraries/blob/68ee5e66de9e40206e849cae2ee57473c7960f54/.github/workflows/publish.yaml

https://github.com/NCARB/MFilesSamplesAndLibraries/commit/ab1036ab7575c6e19a551e031cfdb8f83718487e/checks?check_suite_id=379802581

**Comment by CraigHawker** [comment]
Hi Joe,

I've certainly thought about doing that, at least for the REST API wrapper (as I think that's the only one that makes sense to push to nuget).  My concern really is around ensuring that people realise that this is not a productised/supported solution.

On my diary for 2020 is to look at re-structuring the samples and libraries collection, possibly extracting these out into separate repositories.  At this time it may well make sense to pull the REST API wrapper out into a stand-alone repository, and then enable automatic push to nuget on that.

This would enable us to do more, such as enabling compatibility for different flavours of .NET.

What are your thoughts on this?  Were you using more than the REST API wrapper?

Regards,

Craig.

**Comment by feinoujc** [comment]
Yes, I think that makes a lot of sense. We only use the REST api, so restructuring a repo and package just around that code and samples makes a lot of sense to me.

**Comment by CraigHawker** [comment]
An initial release has been published to nuget: https://www.nuget.org/packages/MFaaP.MFWSClient

This release (1.0.0-alpha) is the first version that explicitly targets .NET standard 2.0 (along with .NET 4.6).  These runtimes were chosen largely due to the fact that the RestSharp library provides nuget packages targeting these runtimes.  Whilst the tests are green, I had to make some changes to the tests due to the way in which the newer builds of RestSharp works, and I have only done a small amount of real-world testing.

Please note that the release in nuget is not the same as the source code here.  This will be published somewhere separate.
