### ISSUE TITLE
Open External Application Sample: appdef not updated

### ISSUE THREAD

**Issue by kagedevelopment** [M-Files/MFilesSamplesAndLibraries#2]
Hi Craig, I noticed that the appdef file for the "Open External Application On Command" sample differed from the other samples. The value in the application element is different and the there isn't a platform element. I had to change these to be consistent with the other samples in order for the application to be successfully installed in M-Files. Not sure if anyone else has had a problem with this but I thought I'd point it out. Thanks for putting this repo together. It's been a big help.

**Comment by CraigHawker** [comment]
Hi @kagedevelopment.

This sample uses an older application definition format (see http://developer.m-files.com/Frameworks/User-Interface-Extensibility-Framework/Application-Definition/#schema-versions), which did not support the <platforms> element (as the only platform it supported was the M-Files desktop).

I have just tested this locally and it seemed to work as-is, both in M-Files 2015.3 and in a pre-release version of M-Files 2018.

Please can you describe what happens when you try and use the sample without the platform element, and what version of M-Files you are testing with?

Thanks.

**Comment by kagedevelopment** [comment]
Hi Craig,

When I was trying to add the app initially, I wasn’t getting any sort of error and the application would simply not work or show any sign of being installed. I tried it again just now and received a very helpful error message I previously had not seen. I’ve attached images of the appdef I used and the error message. I’m in M-Files 2015.3

**Comment by CraigHawker** [comment]
Hi @kagedevelopment

In your screenshot the appdef.xml is using V3 of the schema. You can see this by checking the schema reference in the XML declaration.

In the version in GitHub it uses the v1 schema: https://github.com/M-Files/MFilesSamplesAndLibraries/blob/29c6f01b64fc070275fa99316698c84be5d2b3f3/Samples/UIX%20Applications/OpenExternalApplicationOnCommand/appdef.xml

If you update to the V3 schema then you must provide the platform. If you use the v1 schema (as the sample uses) then you do not.

**Comment by kagedevelopment** [comment]
You're right. I just verified the original code from github and it worked. I must have been doing something else wrong on my initial installation of the application. Apologies for creating this issue erroneously.
