### ISSUE TITLE
Open WebPage

### ISSUE THREAD

**Issue by Annus12** [M-Files/MFilesSamplesAndLibraries#45]
We Want to opening Web Page using mfiles vault Application

**Comment by CraigHawker** [comment]
The Vault Application Framework is a server-side component.  It cannot perform client-side operations such as opening a web page.

You can use the UIX to do this.  [This is a good example to start with](https://github.com/M-Files/MFilesSamplesAndLibraries/blob/master/Samples/UIX%20Applications/OpenExternalApplicationOnCommand/main.js); the primary difference is that you'd use "[MFiles.ExecuteURL](https://userguide.m-files.com/UI_Extensibility_Framework/#MFClientScript~ICommonFunctions~ExecuteURL.html)" to open the web browser, rather than using WScript to run notepad.
