### ISSUE TITLE
UnauthorizedAccessException when using Postman

### ISSUE THREAD

**Issue by DD-UX** [M-Files/MFilesSamplesAndLibraries#9]
Hi team, first of all let me thank you for the collection of Postman requests, is a great impulse for development.

Saying this, when I try to interact with any entity that requires a token, I get a message like the next:

##### Error: 
```
{
    "Status": 403,
    "URL": "/session",
    "Method": "GET",
    "Exception": {
        "Name": "UnauthorizedAccessException",
        "Message": "Login to vault failed"
    },
    "Stack": "ID de referencia de error: <id de referencia de error>",
    "Message": "Login to vault failed",
    "IsLoggedToVault": false,
    "IsLoggedToApplication": false,
    "ExceptionName": "UnauthorizedAccessException"
}
```
##### Steps to reproduce the issue:
1. Run `1. Connection > Login to Vault` and getting the token
2. Implement token globally through the `MFAuthenticationToken` variable
3. Attempt to run `1. Connection > Get Logged in User Information` (or any other resquest)

Is there anything else I might be missing? I've used the same scope to set the `MFWSUrl` and the `MFAuthenticationToken`, both are being recognized by Postman, but only one is working fine.

Thanks in advance for any help or insight you might provide!

![image](https://user-images.githubusercontent.com/9665653/46888018-a9134100-ce35-11e8-880d-6a966fa16d77.png)

**Comment by Rantanen** [comment]
Looking at the Login to Vault item, [it's calling](https://github.com/M-Files/MFilesSamplesAndLibraries/blob/master/Libraries/Postman/M-Files.postman_collection.json#L15-L17) the [/server/authenticationtokens](https://developer.m-files.com/APIs/REST-API/Reference/resources/server/authenticationtokens/) endpoint.

This means the item is somewhat misnamed. That endpoint does _not_ perform a _login_. All it does is calculates the authentication token based on the given inputs. The login (and thus validating the credentials) happens when the authentication token is used for the first time.

So even if your Login to vault request goes through successfully, your credentials and/or the vault GUID might be wrong. You might want to double check that the data included in your Login to Vault request is valid for your environment.

**Comment by CraigHawker** [comment]
@Rantanen is completely correct: it is important to note that this endpoint will return you an authentication token regardless of whether those credentials are correct or not. This is by design.

If you receive a 403 whilst then using that token then the details were likely incorrect in the original request. 

The point about renaming the Postman sample is a good one, though, and will be taken on board.

**Comment by DD-UX** [comment]
Thanks both for your answers. I will review them more in deep and if anything pops will let you know. Thanks!

**Comment by DD-UX** [comment]
Closed, the issue doesn't apply. Thanks!

**Comment by DD-UX** [comment]
To build the token properly, body should be an object stringified (raw):
```
{
    "Username": "<Username>",
    "Password": "<Password>",
    "VaultGuid": "<VaultGuid>"
}
```
